name: FRC Build & Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2-beta
    - name: FRC Build & Test
      uses: Ewpratten/FRC-actions@v1.1.2
      with:
        build_mode: 'all'